#!/bin/bash

echo "🚀 Setting up Supabase for Keva Contact Form"
echo "============================================"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Open your Supabase project dashboard at:"
echo "   https://supabase.com/dashboard/projects"
echo ""
echo "2. Go to SQL Editor"
echo ""
echo "3. Copy and paste this SQL code:"
echo ""
echo "-- Create contacts table"
cat supabase/migrations/001_create_contacts_table.sql
echo ""
echo "4. Click 'Run' to execute the SQL"
echo ""
echo "5. Test your contact form at http://localhost:3000"
echo ""
echo "✅ That's it! Your contact form will now work."
echo ""
echo "📧 Optional: For email notifications, sign up at resend.com"
echo "   and add RESEND_API_KEY to your .env.local file"
echo ""
